name: painter
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: 2.4.10
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
        - asset: assets/fonts/SFProText-BoldItalic.ttf
        - asset: assets/fonts/SFProText-Heavy.ttf
        - asset: assets/fonts/SFProText-HeavyItalic.ttf
        - asset: assets/fonts/SFProText-Light.ttf
        - asset: assets/fonts/SFProText-LightItalic.ttf
        - asset: assets/fonts/SFProText-Medium.ttf
        - asset: assets/fonts/SFProText-MediumItalic.ttf
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-RegularItalic.ttf
        - asset: assets/fonts/SFProText-Semibold.ttf
        - asset: assets/fonts/SFProText-SemiboldItalic.ttf
          style: normal
